language: haskell

# we need to do this explicitly because hspec depends on hspec-expectations...
install:
    - cabal install hspec markdown-unlit silently

script:
  - cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test
